Si/feat/sign up benefit on right hand side
FixItDevs/fix-it pull request #38
Opened 2024-04-25 11:44 UTC by siqbal181

Very basic for now
Not covering conditional based on login status

2024-04-25 11:59 UTC, pablisch requested changes
Great. Glad you did this! 
Personal opinion, for me there is too much side padding/margin. Too much whitespace in such a thin column. 
Sign up feels like it should be the link to signing up, i.e. an onClick that logs that it is clicked for now, and maybe a bit bigger?

The cursor appears as a text input cursor over the benefits but should turn to pointer over the whole benefit div, and the title if that is to be a link. 

Cursor should change but other comments are just opinions and happy for you to decide on those.

2024-04-25 12:50 UTC, siqbal181 commented
@pablisch Changed!

2024-04-29 10:08 UTC, pablisch requested changes
This looks loads better! I think the benefits content needs to be aligned left personally as depending on width, there can be large misalignments.
![Screenshot 2024-04-29 at 11 00 41](https://github.com/FixItDevs/fix-it/assets/19639889/61edd74d-60e8-4d23-beb9-d69b0db98044)
Above is how it appeared to me. I think it would be good to pull into main and make decisions on these small things together. See how it looks, maybe even sit with and have ongoing niggles and minor edits lists.

The issue is it doesn't run for me which is confusing as presumably it runs for you. I get all sorts of errors in the feed which stop any of the page from rendering. I notice there is still a Post folder so it must be behind main. Is everything pushed? Do you need to merge main?

2024-04-30 08:33 UTC, siqbal181 commented
> This looks loads better! I think the benefits content needs to be aligned left personally as depending on width, there can be large misalignments. ![Screenshot 2024-04-29 at 11 00 41](https://private-user-images.githubusercontent.com/19639889/326399661-61edd74d-60e8-4d23-beb9-d69b0db98044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjU4ODgsIm5iZiI6MTcxNDQ2NTU4OCwicGF0aCI6Ii8xOTYzOTg4OS8zMjYzOTk2NjEtNjFlZGQ3NGQtNjBlOC00ZDIzLWJlYjktZDY5YjBkYjk4MDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA4MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NDBjZThmY2FhMmY3NGM0YWI5YmQ5NjVkZGQxYzhiZmIxZTM2OTM5ZTZiMmZiMzU0ODVjNTQ2ZjViM2VmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VqfkDnRMmrxLaExBpzf7sas_Yva3ZaJWWgIj5Wlz-bc) Above is how it appeared to me. I think it would be good to pull into main and make decisions on these small things together. See how it looks, maybe even sit with and have ongoing niggles and minor edits lists.
> 
> The issue is it doesn't run for me which is confusing as presumably it runs for you. I get all sorts of errors in the feed which stop any of the page from rendering. I notice there is still a Post folder so it must be behind main. Is everything pushed? Do you need to merge main?

Very strange. I've merged main so try now?

> This looks loads better! I think the benefits content needs to be aligned left personally as depending on width, there can be large misalignments. ![Screenshot 2024-04-29 at 11 00 41](https://private-user-images.githubusercontent.com/19639889/326399661-61edd74d-60e8-4d23-beb9-d69b0db98044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjU4ODgsIm5iZiI6MTcxNDQ2NTU4OCwicGF0aCI6Ii8xOTYzOTg4OS8zMjYzOTk2NjEtNjFlZGQ3NGQtNjBlOC00ZDIzLWJlYjktZDY5YjBkYjk4MDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA4MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NDBjZThmY2FhMmY3NGM0YWI5YmQ5NjVkZGQxYzhiZmIxZTM2OTM5ZTZiMmZiMzU0ODVjNTQ2ZjViM2VmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VqfkDnRMmrxLaExBpzf7sas_Yva3ZaJWWgIj5Wlz-bc) Above is how it appeared to me. I think it would be good to pull into main and make decisions on these small things together. See how it looks, maybe even sit with and have ongoing niggles and minor edits lists.
> 
> The issue is it doesn't run for me which is confusing as presumably it runs for you. I get all sorts of errors in the feed which stop any of the page from rendering. I notice there is still a Post folder so it must be behind main. Is everything pushed? Do you need to merge main?

Very strange. I've merged main and aligned the text to left. Try now?

2024-04-30 09:37 UTC, pablisch approved these changes
Great. Mystery over. Looks great.

2024-04-30 09:37 UTC, pablisch commented on frontend/src/components/SignUpBenefits/SignUpBenefits.tsx
> +      <span className="sign-up-title" onClick={() => handleSignUpClick()}>
Small detail. className should probably be sign-up-benefits-title or benefits-title as sign-up-title will almost certainly be needed on the sign-up page. 
I notice on line 31, benefit-text is used but sign-up-benefit-... for most. If brevity is a concern then I think benefits-... would be perfectly reasonable. I don't see any potential clashes with that.

2024-05-01 12:13 UTC, merged