DRAFT Si/feat/posts
FixItDevs/fix-it pull request #41
Opened 2024-04-25 14:07 UTC by siqbal181

2024-04-25 15:21 UTC, pablisch requested changes
Fine with specific colours being in fine but if we are likely to use them elsewhere, it would be good to get them as variables.

2024-04-25 15:21 UTC, pablisch commented on frontend/src/components/PostItem/PostItem.css
> +  color: #05473d;
Can we keep colours as variables in index.css as much as is practical.

2024-04-25 15:21 UTC, pablisch commented on frontend/src/components/PostItem/PostItem.tsx
> +        <h2 className="post-title">{postText.title}</h2>
title and body are duplicated here.

2024-04-29 11:28 UTC, pablisch commented
Feels like there is way too much going on in this branch. I've looked at the infinite scroll and all looks good so I can't see why it is not working, though of course I have no idea what makes infinite scroll works but feels like what was working should have been merged in before infinite scroll started as it is a whole new parade.

When I got onto the branch, I got a load of errors and started adding stuff to fix them before I realised I probably needed to npm install instead. I added some logs for visibility and it is all on a new branch, sipj/feat/infinite-scroll, it does not really add much of any value but jump on it for visibility if you like.

The main thing is that looking at the blog, it looks like you've done everything right. Some changes from the blog code but they all felt like improvements. Perhaps the improvements are the problem? I think my next step would be to create a sample project using infinite scroll to see if it works in isolation. It could be that our existing code is interfering, especially the scroll CSS we already have.

2024-04-29 11:29 UTC, pablisch commented
There are also now 13 posts in the test db if that helps for infinite testing.

BTW, I am sure you are already aware but the get more posts function works but is never called by infinite scroll.

2024-05-01 11:17 UTC, siqbal181 commented on frontend/src/components/FeedColumn/FeedColumn.tsx
> +      .get("http://localhost:3000/api/v1.0/posts", {
stick to prev version of async await

2024-05-07 13:51 UTC, merged